web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.resende.biz'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.resende.biz'
  ports:
    - '8080:80'
    - '4430:443'
    - '220:22'
  volumes:
    - './config:/etc/gitlab'
    - './logs:/var/log/gitlab'
    - './data:/var/opt/gitlab'
